name: publish-to-test-pypi

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6

      - name: Install hatch
        run: uv tool install hatch

      - name: Inject unique build tag into VERSION file
        run: |
          BASE_VERSION=$(cat VERSION)
          BUILD=".dev${{ github.run_id }}${{ github.run_number }}${{ github.run_attempt }}"
          echo "${BASE_VERSION}${BUILD}" > VERSION

      - name: Build distributions with uv
        run: uv build --wheel

      - name: Upload distributions as artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #  v6.0.0
        with:
          name: python-package-distributions-${{ github.run_id }}
          path: dist/

  publish-to-test-pypi:
    name: Publish Python distribution to TestPyPI
    needs: [build]
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/python-em511

    permissions:
      id-token: write

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 #  v6.0.0
        with:
          name: python-package-distributions-${{ github.run_id }}
          path: dist/

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
